### PR TITLE
Update PL (2.8 beta 13)

### PR DESCRIPTION
**Pull request by BeckyDTP**
I was prepare the last amendments in the Polish translation based on the 2.8 beta 13 version.

### CODE REVIEW

**Comment by BeckyDTP** [comment]
Additional:
1. http://i.imgur.com/nw5eLuv.png
2. In 2.8 beta 13 not working FBReader book network (in free version 2.7.15 is OK).
Message: Nie udało się połączyć z serwerem books.fbreader.org (Failed to connect to host books.fbreader.org)

**Comment by geometer** [comment]
1. Fixed too, thanks (the file is in another repo at the moment).
2. Very strange. It works fine on my devices. Maybe temporary server failure?

**Comment by BeckyDTP** [comment]
Ad 1. Thank you.
Ad 2. What else can I check?
http://i.imgur.com/q7tdNL8.png

**Comment by geometer** [comment]
No idea. :( In principle, you can try with premium non-beta, but this requires to re-install the app. Not sure this makes sense, beta 14 will be uploaded in two days, with new connection mechanism.

**Comment by BeckyDTP** [comment]
Thank you. I will wait for beta 14 and let you know.

**Comment by geometer** [comment]
Ahh, I know a *quick* test. Try to switch on synchronisation in Settings -> Synchronisation. In Premium, I mean.

**Comment by BeckyDTP** [comment]
I was try it many times :(
Checkbox does not want to turn on.
First "Trying to connect. Please wait…", and later "Failed to connect to host books.fbreader.org"

Interesting, other networks not working in Premium too (for example Smashwords, Wolne Lektury etc.).
In free version all networks working OK.

**Comment by geometer** [comment]
Very strange. Was it working before beta 13? Maybe some device settings that disables network features for the specific app?

One more quick test: right menu, "start screen". Can it show/download the "default" books? The start screen connects the network in a different way; so if it does work, I guess the issue is in the reader code, otherwise in device settings.

**Comment by BeckyDTP** [comment]
This is the first such case on my smartphone.
Start screen in Premium (beta) is strange too:
http://i.imgur.com/bScUlYE.png
No covers, after clicking nothing happens.

**Comment by geometer** [comment]
I was wrong; it uses the same network technique.

**Comment by BeckyDTP** [comment]
One more thing. Premium (beta) version I bought yesterday, so I did not check earlier versions. I saw that in the free version – network works, covers are visible, and books from "start screen" are downloadable.

**Comment by geometer** [comment]
Ahh. So this means you can safely reinstall it. Please try, maybe something went wrong during installation.

**Comment by BeckyDTP** [comment]
OK.
1. Uninstall Premium Beta
2. Install again
3. All works! (book networks, covers)
4. Thank you!

**Comment by geometer** [comment]
Great. Just to be sure: is it still 2.8 beta 13? (FBReader -> Settings -> About the app.)

**Comment by BeckyDTP** [comment]
Yes. 2.8 beta 13 (2076302)

**Pull request merged**
