### PR TITLE
Polish translation (update and typos)

### PR DESCRIPTION
**Pull request by BeckyDTP**

### CODE REVIEW

**Comment by geometer** [comment]
Dziękuję! :)

**Comment by geometer** [comment]
I have an issue with Polish files. I got two updates from two people in the same time. :) One (your) merged into 3.0 branch, the second one is in master. I've merged all non-conflicting and obvious changes (e.g., your typos & punctuations). But I cannot make decisions for strings translated from scratch. Could you please help me with this? I do ask you because the second person is not familiar with git.

**Comment by BeckyDTP** [comment]
Of course I will help. If you can show me lines (in gist?) with issues I will select better translation (sometimes mine, sometimes by Maciej Bator) or prepare mix. If I will have additional question – I will ask you, for the translation was best.

**Comment by BeckyDTP** [comment]
To clarify. 
`<node name="byPageNo" value="wg liczby stron"/>`
should by:
`<node name="byPageNo" value="**wg numeru strony**"/>`
…because this is order the bookmarks.

**Comment by geometer** [comment]
Ok, the diff is here: https://github.com/geometer/fbreader-module-resources/compare/master...3.0-pl

**Comment by geometer** [comment]
2.8 beta 13 with all your changes uploaded to the Play Store (click https://play.google.com/apps/testing/com.fbreader if you are not a beta tester yet).

**Comment by BeckyDTP** [comment]
I'm beta tester and Premium user too.

**Pull request merged**
